### ISSUE TITLE
Feedback for “03 Borrow”

### ISSUE THREAD

**Issue by szaross** [kpietak/rust-course#1]
Dwa pierwsze przykłady z kodem w podrozdziale "Praca z referencjami" są identyczne.

[link](https://kpietak.github.io/rust-course/02-ownership/03-borrow/#praca-z-referencjami)

**Comment by kpietak** [comment]
Dziękuję za zgłoszenie!

W nowej wersji pojawiły się dwa nowe przykłady (już bez duplikacji ;) ).
